name: suggest-alt-text

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  suggest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install torch pillow pytesseract
      - name: Suggest alt text
        run: |
          for file in $(find . -name '*.md'); do
            python suggest_alt_text.py $file
          done
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: Suggested alt text for inline images
